version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-typescript-get-names-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1df1hjf2lfia3"
s3_prefix = "sam-typescript-get-names-app"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
